spring.application.name=coffee-shop-api

# Database configuration (MySQL - JPA)
spring.datasource.url=jdbc:mysql://localhost:3306/coffee_shop
spring.datasource.username=coffeeshop
spring.datasource.password=coffeeshop

# MongoDB configuration
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=coffee_db